name: Build Windows EXE
on: [push] 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/upload-artifact@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --icon=app.ico main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v2
        with:
          name: EcoProgPy-Windows
          path: dist/
